sonar.projectKey=week12-sonarqube-docker-cicd
sonar.projectName=Week12 SonarQube Docker CICD
sonar.projectVersion=1.0
sonar.sources=.
sonar.exclusions=**/__pycache__/**,**/*.pyc
sonar.python.version=3.11